version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: user1
      KC_DB_PASSWORD: password1
      KEYCLOAK_ADMIN: admin1
      KEYCLOAK_ADMIN_PASSWORD: admin1
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge
    command:
      - start-dev
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - keycloak_network1

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - keycloak_network1

volumes:
  postgres_data1:

networks:
  keycloak_network1: